### ISSUE TITLE
Threading not working on Mac in Experimental

### ISSUE THREAD

**Issue by jvcleave** [gameoverhack/ofxOpenNI#13]
I can't seem to get Threading to work on OS X 10.6 (haven't tried 10.7)

the app compiles, finds the kinect, starts the generators but never opens a window

**Comment by gameoverhack** [comment]
Yes sorry there's a weird conflict between how windows and osx need to call scoped mutex's. I'll have to use some kind of ugly define it seems...I'm in transit for the next 20 hours, so for now just search replace (mutex) with ()

**Comment by roymacdonald** [comment]
Hi, I just came across this issue and found out it was because of using lock(mutex) instead of lock(). I'm on osx 10.6 BTW.
Have you fixed this issue? 
I can add that precompiler defines and PR. Is it ok for you?

cheers!

**Comment by kylemcdonald** [comment]
on the current experimental branch i get an app that opens, and tracks the skeleton, but once the skeleton goes out of the scene then the ScopedLock line stalls the app indefinitely.

also, i think ScopedLock will only work if it's outside of the if(){} otherwise the "scope" is just going to be that block of if(){} code, not the whole function?

edit: argh, really hard to debug this. i'm not really sure what's going on. i'm reverting back to master, it's a shame because the experimental API is so much cleaner :(
